// frontend/src/redux/constants/solutionConstants.js
export const SOLUTION_LIST_REQUEST = 'SOLUTION_LIST_REQUEST';
export const SOLUTION_LIST_SUCCESS = 'SOLUTION_LIST_SUCCESS';
export const SOLUTION_LIST_FAIL = 'SOLUTION_LIST_FAIL';

export const SOLUTION_CREATE_REQUEST = 'SOLUTION_CREATE_REQUEST';
export const SOLUTION_CREATE_SUCCESS = 'SOLUTION_CREATE_SUCCESS';
export const SOLUTION_CREATE_FAIL = 'SOLUTION_CREATE_FAIL';
